---
driver:
  name: vagrant
  customize:
    memory: 2048

  #name: digitalocean

provisioner:
  name: shell

platforms:
  - name: bento/ubuntu-16.04

  #- name: ubuntu-16-04-x64
  #  driver_config:
  #    size: 2gb

busser:
  ruby_bindir: /usr/bin

suites:
  - name: default
